title = " Kruba Sagari S"
baseURL = "https://example.com/"
theme = "my-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Tirupur, India"
favicon = "/favicon.ico"
firstName = "Kruba Sagari "
lastName = "Shanmugam"
phone = "1-555-555-1234"
showSocializations = true
showContact = false
sections = ["skills","publications","creations","contributions","experience","education","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/kruba-sagari-shanmugam-6bbb12326/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/Krubasagari2006"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"